### ISSUE TITLE
Mockups/Design

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nomad-status-panel#1]
es_ES:

Bueno bro @NiconDevTeam vamos a ir viendo que ir haciendo vale.

![](http://i.imgur.com/EiHAwfA.png)

Lo primero es que para lograr una experiencia diferente iremos reemplazando el plasmoid de la bandeja del sistema por applets individuales, de igual manera que otros sistemas. El primero sería el de multimedia.

El wireframe de arriba es sobre la idea en general del widget/plasmoid. Lo principal es que a diferencia de como actualmente está en la bandeja de sistema la ventana es separada del panel (como los indicadores en Unity). Lo siguiente es su tamaño más justo y los botones de un mismo tamaño. También la barra del tiempo con el tiempo actual y el restante de el medio en reproducción (en este caso una canción) y dos botones una para aleatorio y otro para repetir.

En la parte superior derecha un botón que abre las preferencias del plasmoid. El arte del álbum (si está disponible) y la información del medio.

Aquí las medidas, la ventana del widget mide 336x272.

![](http://i.imgur.com/wI41zWw.png)
#

**Comment by NiconDevTeam** [comment]
hola @UriHerrera , ok perfecto, ya estoy creando el plasmoide con las especificaciones requeridas, claro que en estos momentos estoy leyendo el API de plasma para el tema de posicionar el plasmoide y los diferentes eventos provistos por el mismo, espero tenerlo listo en un lapso maximo de dos semanas, 

Para manejar el standar de KDE entonces nombrare el paquete como: **org.kde.nitrux** y para el plugin podria contener un nombre como **Nitrux Media Controller**

**Comment by UriHerrera** [comment]
> Para manejar el standar de KDE entonces nombrare el paquete como: org.kde.nitrux y para el plugin podria contener un nombre como Nitrux Media Controller

Yo creo que mejor usamos org.nitrux.menubar-player para el nombre de el paquete. El nombre si estaría bien.

**Comment by NiconDevTeam** [comment]
Aqui publico una previa de como va quedando nuestro nuevo plasmoid, ya se esta terminando de ajustar la UI en estos momentos estoy programando otros eventos adicionales, y ajustando el tema de los iconos que usaremos para los botones
![screenshot_20161102_234350](https://cloud.githubusercontent.com/assets/1855499/19956114/839fcb22-a156-11e6-9964-e1db64b46342.png)

**Comment by NiconDevTeam** [comment]
@UriHerrera hola amigo, aqui te envio un screen sobre el avance del plasmoid, en estos momentos nos encontramos en un 70% de desarrollo segun el requerimiento, espero tus comentarios y observaciones.
![screenshot_20161104_002757](https://cloud.githubusercontent.com/assets/1855499/19995480/93a866ee-a225-11e6-897d-80b9f8413485.png)
